SportsStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int Totalpages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage); }
        }
    }
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

SportsStore.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository _repository;

        public AdminController(IProductRepository repo)
        {
            _repository = repo;
        }
        //
        // GET: /Admin/

        public ViewResult Index()
        {
            return View(_repository.Products);
        }

        // GET: /Edit/
        public ViewResult Edit(int productId)
        {
            Product product = _repository.Products.FirstOrDefault(c => c.ProductId == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveProduct(product);
                TempData["message"] = String.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(product);
            }
        }
    }
}

SportsStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository _repository;
        private IOrderProcessor _orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor orderProcessor)
        {
            _repository = repo;
            _orderProcessor = orderProcessor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
                {
                    Cart = cart,
                    ReturnUrl = returnUrl
                });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product!=null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new {returnUrl});
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository _repository { get; set; }

        public NavController(IProductRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _repository.Products.Select(x => x.Category).Distinct().OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository)
        {
            _repository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            var model = new ProductsListViewModel
                {
                    Products = _repository.Products
                                          .Where(p=>category==null || p.Category==category)
                                          .OrderBy(p => p.ProductId)
                                          .Skip((page - 1) * PageSize)
                                          .Take(PageSize),
                    PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = PageSize, TotalItems = category==null?_repository.Products.Count():_repository.Products.Count(e => e.Category==category) },
                    CurrentCategory = category
                };

            return View(model);
        }
    }
}

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit" + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.EditorForModel()
    <input type="submit" value="Save" />
    
    @Html.ActionLink("Cancel and return to list", "Index")
}

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>All Products</h1>

<table class="Grid">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th class="NumericCol">
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Edit", new { item.ProductId })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="NumericCol">
                @item.Price.ToString("c")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("ProductId", item.ProductId)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }

</table>
<p>@Html.ActionLink("Add a new product", "Create")</p>

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Sports Store: Checkout";
}

<h2>Checkout now</h2>
Please enter your address, and we'll ship your goods right away
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <h3>Ship to</h3>
    <div>Name: @Html.EditorFor(m=>m.Name)</div>
    
    <h3>Address</h3>
    <div>Line1: @Html.EditorFor(m=>m.Line1)</div>
    <div>Line2: @Html.EditorFor(m=>m.Line2)</div>
    <div>Line3: @Html.EditorFor(m=>m.Line3)</div>
    <div>City: @Html.EditorFor(m=>m.City)</div>
    <div>State: @Html.EditorFor(m=>m.State)</div>
    <div>Zip: @Html.EditorFor(m=>m.Zip)</div>
    <div>Country: @Html.EditorFor(m=>m.Country)</div>
    
    <h3>Options</h3>
    <label>
        @Html.EditorFor(m=>m.GiftWrap)
        Gift wrap these items
    </label>
    
    <p><input class="actionButtons" type="submit" value="Complete order"/></p>
}

SportsStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "SportsStore: Order Submitted";
}

<h2>Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible.

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Sports Store: Your Cart";
}

<h2>Your Cart</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">Quantity</th>
            <th align="left">Item</th>
            <th align="right">Price</th>
            <th align="right">SubTotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td align="center">@line.Quantity</td>
                <td align="left">@line.Product.Name</td>
                <td align="right">@line.Product.Price</td>
                <td align="right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="actionButtons" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Total:</td>
            <td align="right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons"><a href="@Model.ReturnUrl">Continue shopping</a>@Html.ActionLink("Checkout Now","Checkout")</p>

SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart

<div id="cart">
    <span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),
        @Model.ComputeTotalValue().ToString("c")
    </span>
    @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)

</div>

SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product")

@foreach (var linkText in Model)
{
    @Html.RouteLink(linkText, new { controller = "Product", action = "List", category = linkText, page = 1 }, new { @class = linkText == ViewBag.SelectedCategory ? "selected" : null })
}

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    Html.RenderPartial("ProductSummary", p);
}

<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory}))
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description
    
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        @Html.HiddenFor(x=>x.ProductId)
        @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
        <input type="submit" value="+ Add to cart"/>
    }
    <h4>@Model.Price.ToString("c")</h4>
</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css"/>
    <title></title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet"/>
</head>
<body>
    <div id="header">
        @{
            Html.RenderAction("Summary", "Cart");
        }
        <div class="title">SPORTS STORE</div>
    </div>
    <div id="categories">
        @{ Html.RenderAction("Menu", "Nav"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>